<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenAI" Version="2.0.0-beta.10" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Promts\Promt.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Promt.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Promts\Promt.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Promt.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AiErrorHandler.Models\AiErrorHandler.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Promts\RussianLanguagePrompt.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Promts\BasePrompt.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
