//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiErrorHandler.Core.Promts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Promt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Promt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AiErrorHandler.Core.Promts.Promt", typeof(Promt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a .NET 7 expert specializing in exception analysis and debugging. I will provide you with an exception and its stack trace from a .NET 7 application.
        ///
        ///Please analyze the provided exception and stack trace thoroughly, considering:
        ///- The specific exception type and its meaning in .NET 7 context
        ///- The root cause based on the stack trace analysis
        ///- Common scenarios that lead to this type of exception
        ///- Best practices for prevention and resolution
        ///- .NET 7 specific considerations and features that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePrompt {
            get {
                return ResourceManager.GetString("BasePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT: Respond in Russian language using the following structure:
        ///
        ///## РљР РђРўРљРР™ РђРќРђР›РР—
        ///- **РћС€РёР±РєР°:** [РќР°Р·РІР°РЅРёРµ Рё С‚РёРї РёСЃРєР»СЋС‡РµРЅРёСЏ]
        ///- **РћРїРёСЃР°РЅРёРµ РѕС€РёР±РєРё:** [РљСЂР°С‚РєРѕРµ РѕР±СЉСЏСЃРЅРµРЅРёРµ С‡С‚Рѕ РїСЂРѕРёР·РѕС€Р»Рѕ]
        ///- **Р’РѕР·РјРѕР¶РЅС‹Рµ РїСѓС‚Рё СЂРµС€РµРЅРёСЏ:** [2-3 РѕСЃРЅРѕРІРЅС‹С… СЃРїРѕСЃРѕР±Р° РёСЃРїСЂР°РІР»РµРЅРёСЏ]
        ///
        ///## РџРћР”Р РћР‘РќР«Р™ РђРќРђР›РР—
        ///- **Р”РµС‚Р°Р»СЊРЅРѕРµ РѕРїРёСЃР°РЅРёРµ РїСЂРѕР±Р»РµРјС‹:** [РџРѕРґСЂРѕР±РЅРѕРµ С‚Рµ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RussianLanguagePrompt {
            get {
                return ResourceManager.GetString("RussianLanguagePrompt", resourceCulture);
            }
        }
    }
}
